### ISSUE TITLE
error build app on ubuntu 16.04

### ISSUE THREAD

**Issue by progserega** [mujx/nheko#303] opened 2018-04-22 09:05 UTC
QT 5.7
Ubuntu 16.04 amd64

nheko checkout from git:

commit ca66940ec39047eada21f7900bf0e49d61cb45fb
Author: Konstantinos Sideris <sideris.konstantin@gmail.com>
Date:   Sat Apr 14 14:12:36 2018 +0300

    Popup improvements
    
    - ESC closes the popup.
    - Up/Down arrows for navigation.
    - BackTab for backwards navigation.
    
    fixes #301
    fixes #302

building error:
/home/Serega/work/matrix/nheko/src/timeline/TimelineView.cc:798: ошибка: cannot call member function 'mtx::events::EventType TimelineView::getEventType(const TimelineEvents&) const' without object
                 return mtx::events::EventType::RoomMessage == getEventType(event);
                                                            ^
/usr/include/c++/5/bits/predefined_ops.h:234: ошибка: void value not ignored as it ought to be
  { return bool(_M_pred(*__it)); }
                              ^

/home/Serega/work/matrix/nheko/src/timeline/TimelineView.cc:808: ошибка: cannot call member function 'mtx::events::EventType TimelineView::getEventType(const TimelineEvents&) const' without object
                 return mtx::events::EventType::RoomMessage == getEventType(event);
                                                            ^

/usr/include/c++/5/bits/predefined_ops.h:234: ошибка: void value not ignored as it ought to be
  { return bool(_M_pred(*__it)); }
                              ^

**Comment by progserega** [comment] 2018-04-22 09:06
![error1](https://user-images.githubusercontent.com/1297163/39093290-477d7c10-4660-11e8-9069-b08866d2b90a.png)
build log

**Comment by progserega** [comment] 2018-04-22 09:07
[build.log](https://github.com/mujx/nheko/files/1935362/build.log)
build log

**Comment by mujx** [comment] 2018-04-22 09:08
Duplicate of #298 . Try with gcc-7 or clang (minimum required versions for compilers are also mentioned in the readme)

**Closed by mujx** 2018-04-22 09:08 UTC

**Comment by progserega** [comment] 2018-04-22 11:13
In README:

On Ubuntu 14.04 Trusty, it's possible to use GCC 4.9.4+, but it is not recommended, because it requires installing GCC packages from third-party PPAs. **Later versions of Ubuntu that come with GCC 4.9.4+ should work with GCC out-of-the-box.**

I use ubuntu 16.04. May be remove this text from readme?
