### ISSUE TITLE
Crashes on start: parse error - unexpected 'q'

### ISSUE THREAD

**Issue by alphapapa** [mujx/nheko#151] opened 2017-12-06 16:35 UTC
### System:

- Nheko commit/version: ae4edba22da01d42134e0e59139ea142ef665252
- Operating System: Ubuntu Trusty 14.04
- Qt version:  5.9.2
- C++ compiler: Clang 3.6
- Desktop Environment: KDE 4

### Actual behavior

Crashes on launch after several seconds of 100% CPU usage.

### Expected behavior

The program should finish starting and the window should appear.

### Steps to reproduce

Run `nheko`.

### Debugger traceback 
```
     4.220: [debug] - Setting up cache
     4.221: [debug] - Restoring state from cache
     4.221: [debug] - Restored nextBatchToken "s358612438_342015580_894564_72248725_25526005_202867_2779401_3233353_2381"
terminate called after throwing an instance of 'std::invalid_argument'
  what():  parse error - unexpected 'q'
```

Thanks.

**Comment by mujx** [comment] 2017-12-06 16:38
Duplicate of #144.

**Closed by mujx** 2017-12-06 16:38 UTC

**Comment by alphapapa** [comment] 2017-12-06 17:04
Thank you.
