### ISSUE TITLE
Can't sign in after installing RPM or with the AppImage - SSL error

### ISSUE THREAD

**Issue by Toj** [mujx/nheko#280] opened 2018-03-19 22:36 UTC
### System:

- Nheko commit/version: 0.2.1
- Installation method: Tried the .rpm installation and running the AppImage
- Operating System: Fedora 27
- Qt version: 4.8.7 (I think according to pkg-config --modversion QtCore)
- Desktop Environment: XFCE

### Actual behavior

Attempting to sign in with my matrix ID and password fails with the following message at the bottom of the screen

**Error creating SSL context (error:140A90C4:SSL routines:func(169):reason(196))**

Log shows 
```

    34.769: [warning] - QSslSocket: cannot resolve CRYPTO_num_locks
    34.770: [warning] - QSslSocket: cannot resolve CRYPTO_set_id_callback
    34.770: [warning] - QSslSocket: cannot resolve CRYPTO_set_locking_callback
    34.770: [warning] - QSslSocket: cannot resolve ERR_free_strings
    34.770: [warning] - QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
    34.770: [warning] - QSslSocket: cannot resolve EVP_CIPHER_CTX_init
    34.770: [warning] - QSslSocket: cannot resolve sk_new_null
    34.770: [warning] - QSslSocket: cannot resolve sk_push
    34.770: [warning] - QSslSocket: cannot resolve sk_free
    34.770: [warning] - QSslSocket: cannot resolve sk_num
    34.770: [warning] - QSslSocket: cannot resolve sk_pop_free
    34.770: [warning] - QSslSocket: cannot resolve sk_value
    34.770: [warning] - QSslSocket: cannot resolve SSL_library_init
    34.770: [warning] - QSslSocket: cannot resolve SSL_load_error_strings
    34.770: [warning] - QSslSocket: cannot resolve SSL_get_ex_new_index
    34.771: [warning] - QSslSocket: cannot resolve SSLv23_client_method
    34.771: [warning] - QSslSocket: cannot resolve SSLv23_server_method
    34.771: [warning] - QSslSocket: cannot resolve X509_STORE_CTX_get_chain
    34.771: [warning] - QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
    34.771: [warning] - QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
    34.771: [warning] - QSslSocket: cannot resolve SSLeay
    34.771: [warning] - QSslSocket: cannot resolve SSLeay_version
    34.771: [warning] - Incompatible version of OpenSSL
    34.904: [warning] - QSslSocket: cannot call unresolved function SSLv23_client_method
    34.911: [warning] - QSslSocket: cannot call unresolved function SSL_library_init
    38.863: [warning] - QSslSocket: cannot call unresolved function SSLv23_client_method
    38.863: [warning] - QSslSocket: cannot call unresolved function SSL_library_init
    62.444: [warning] - QSslSocket: cannot call unresolved function SSLv23_client_method
    62.444: [warning] - QSslSocket: cannot call unresolved function SSL_library_init
    65.935: [warning] - QSslSocket: cannot call unresolved function SSLv23_client_method
```

**Comment by simoniz0r** [comment] 2018-03-19 22:42
There's a [release of nehko on the Fedora Copr](https://copr.fedorainfracloud.org/coprs/xvitaly/matrix/) that should work fine and install any necessary deps that you might be missing.

**Comment by mujx** [comment] 2018-03-20 07:04
Apparently this is related to [this Debian issue](https://github.com/AppImage/AppImageKit/wiki/Desktop-Linux-Platform-Issues#openssl) regarding openssl. I'm not sure why this also happens in Fedora.

@Toj Could you try @simoniz0r 's suggestion and install nheko from the fedora repos? There is also a mention in the README.

**Comment by xvitaly** [comment] 2018-03-20 14:25
> There's a release of nehko on the Fedora Copr that should work fine and install any necessary deps that you might be missing.

But I have problem with building latest nheko releases on Fedora 26-27 due to [GCC 7.3.1 regression](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84785). I don't know when this issue will be fixed in Fedora stable repositories. Building for Fedora 28+ works fine (GCC 8.0.1 is used).

**Comment by mujx** [comment] 2018-05-09 09:42
Closing this in favor of #156

**Closed by mujx** 2018-05-09 09:42 UTC
