### ISSUE TITLE
No Easy Way To Join Channels

### ISSUE THREAD

**Issue by BrainBlasted** [mujx/nheko#70] opened 2017-09-24 23:34 UTC
So, I found a usability issue while testing out this app: There is not an easy way to find or join new channels. Trying to use commands to join was a pain, and I couldn't find the right way to type it so I landed in the correct channel. There was another issue that I will report separately.

**Comment by mujx** [comment] 2017-09-25 07:25
Actually there is no way to join a channel 😛. Closing as duplicate of #25

**Closed by mujx** 2017-09-25 07:25 UTC

**Comment by BrainBlasted** [comment] 2017-09-25 12:43
Ah, my bad. Was looking to see if there was another issue on this
