### ISSUE TITLE
Clicking on an image doesn't open it on the same screen as the nheko window.

### ISSUE THREAD

**Issue by Qwertie-** [mujx/nheko#272] opened 2018-03-14 22:47 UTC
### System:

OS: Fedora 27
DE: Gnome
Package version: nheko-0.2.0-1.fc27.x86_64 (from fedora repo)

### Actual behavior
Window is on my right screen, images open on the left screen
### Expected behavior
Images to open on the same screen as window.

**Comment by mujx** [comment] 2018-03-14 23:01
Duplicate of #59

**Closed by mujx** 2018-03-14 23:01 UTC
