### ISSUE TITLE
Emojis are invisible with HiDPI

### ISSUE THREAD

**Issue by vanyasem** [mujx/nheko#140] opened 2017-11-26 12:25 UTC
Emojis are invisible when typed in a message box

### System:

- Nheko commit/version: AUR
- Operating System: Arch Linux x86_64
- Qt version: 5.9.3
- Desktop Environment: KDE Plasma 5.11.3 (KDE Frameworks 5.40.0)

### Expected behavior
Emojis are visible
### Actual behavior
Emojis are invisible
![2017-11-26-151955_868x288_scrot](https://user-images.githubusercontent.com/13350458/33239901-5528991a-d2bd-11e7-9080-c15d173f447c.png)
### Steps to reproduce
Open Emojis panel and select any emoji on a HiDPI setup

**Comment by mujx** [comment] 2017-11-26 12:36
That's another qt bug I'm afraid. The 5.9.2 version doesn't have that problem.

**Comment by mujx** [comment] 2017-11-26 12:41
Reported https://bugreports.qt.io/browse/QTBUG-64313

**Comment by vanyasem** [comment] 2017-11-26 13:20
they are not painted at the wrong place, the panel is totally fine. they are invisible in the text box

**Comment by vanyasem** [comment] 2017-11-26 13:23
thank you, will follow that up

**Comment by mujx** [comment] 2017-12-13 20:46
Closing this because `Qt v5.10` which solves the issue is now available on arch linux.

**Closed by mujx** 2017-12-13 20:46 UTC

**Comment by vanyasem** [comment] 2017-12-14 09:33
Confirmed fixed

**Comment by MTRNord** [comment] 2017-12-14 09:35
We might as this is now a thing Update the ci Version for Windows :) (just a little offtopic but propably related)

**Comment by mujx** [comment] 2017-12-14 09:47
@MTRNord Is the windows build also affected by this bug? We currently use qt5.8 and the latest available version on appveyor is qt5.9.2.

**Comment by MTRNord** [comment] 2017-12-14 10:13
@mujx not really sure but either way we should keep it at the newewst Version instead on letting it creep at the old Version. I think emoji still dont work on Windows (I might be misstaken... I will check for this issue and if emoji work at all later this day)
