### ISSUE TITLE
[AppImage]New crash on startup

### ISSUE THREAD

**Issue by simoniz0r** [mujx/nheko#145] opened 2017-12-05 17:19 UTC
### System:
Nheko commit/version: 6415c4125f296c3d32946c1ea66256f1dad0a1eb
Operating System: OpenSUSE Tumbleweed and Ubuntu 18.04 daily
Qt version: 5.9.2
C++ compiler: N/A
Desktop Environment: LXQt

### Actual behavior
nheko crashes on startup with the error message below.  I tried removing both the cache dir and the config file, but no dice.

### Expected behavior
No crash on startup

### Steps to reproduce
Download the latest AppImage as of commit 6415c4125f296c3d32946c1ea66256f1dad0a1eb and try to run it.

### Debugger traceback 
```
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
[1]    9705 abort (core dumped)  nheko
```

**Comment by mujx** [comment] 2017-12-05 20:54
This is weird because I can reproduce with the nightly build but not if I create the AppImage locally.

**Comment by mujx** [comment] 2017-12-05 21:20
I remember having a similar issue (`std::regex_error`) using clang but I don't why the build didn't fail in this case. 

Anyway, it seems to be fixed with the latest nightly. Please reopen if the issue persists.

**Closed by mujx** 2017-12-05 21:20 UTC
