### ISSUE TITLE
Crash on start or new login

### ISSUE THREAD

**Issue by xvitaly** [mujx/nheko#153] opened 2017-12-06 18:00 UTC
### System:

- Nheko commit/version: latest Git snapshot
- Operating System: Fedora 27
- Qt version: 5.9.1
- C++ compiler: GCC 7.2.1
- Desktop Environment: KDE

### Actual behavior
Crash on start or new login.

### Expected behavior
Normal launch.

### Steps to reproduce
Build and run nheko.

### Debugger traceback 

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  parse error - unexpected 'q'
```

Backtrace:
```
(gdb) bt full
#0  0x00007ffff50f169b in raise () from /lib64/libc.so.6
#1  0x00007ffff50f33b1 in abort () from /lib64/libc.so.6
#2  0x00007ffff5a9d025 in __gnu_cxx::__verbose_terminate_handler() ()
   from /lib64/libstdc++.so.6
#3  0x00007ffff5a9ac16 in ?? () from /lib64/libstdc++.so.6
#4  0x00007ffff5a9ac61 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007ffff5a9aea4 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x000055555562cfa1 in nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>::parser::unexpect(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>::lexer::token_type) const ()
#7  0x0000555555634d98 in nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>::parser::parse_internal(bool) ()
#8  0x00005555556270e0 in Cache::states() ()
#9  0x000055555563bc21 in ChatPage::loadStateFromCache() ()
#10 0x000055555563c1a8 in ChatPage::bootstrap(QString, QString, QString) ()
#11 0x000055555564c626 in MainWindow::showChatPage(QString, QString, QString) ()
#12 0x000055555564d581 in MainWindow::MainWindow(QWidget*) ()
#13 0x00005555555e725f in main ()
```

**Comment by PureTryOut** [comment] 2017-12-06 18:33
Duplicate of #144

**Closed** 2017-12-06 18:53 UTC
