### ISSUE TITLE
[warning] - Incompatible version of OpenSSL

### ISSUE THREAD

**Issue by oonimooni** [mujx/nheko#312] opened 2018-05-02 22:36 UTC
### System:

- Nheko version:  i dont know i downloaded it from https://github.com/mujx/nheko#nightly-releases 
- Installation method: AppImage
- Operating System: Debian Template inside Qubes
- Qt version: -
- C++ compiler: - 
- Desktop Environment:Complex read about qubes-os

### Actual behavior

cant login and work

### Expected behavior

should login and work

### Steps to reproduce

try to login but you cant 

### Terminal Debug (which i have)

```
user@host:~/Desktop$ firejail --noprofile ./nheko-x86_64.AppImage 
Parent pid 2045, child pid 2046
Child process initialized
    12.957: [warning] - QSslSocket: cannot resolve CRYPTO_num_locks
    12.957: [warning] - QSslSocket: cannot resolve CRYPTO_set_id_callback
    12.957: [warning] - QSslSocket: cannot resolve CRYPTO_set_locking_callback
    12.957: [warning] - QSslSocket: cannot resolve ERR_free_strings
    12.957: [warning] - QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
    12.957: [warning] - QSslSocket: cannot resolve EVP_CIPHER_CTX_init
    12.957: [warning] - QSslSocket: cannot resolve sk_new_null
    12.957: [warning] - QSslSocket: cannot resolve sk_push
    12.957: [warning] - QSslSocket: cannot resolve sk_free
    12.957: [warning] - QSslSocket: cannot resolve sk_num
    12.957: [warning] - QSslSocket: cannot resolve sk_pop_free
    12.957: [warning] - QSslSocket: cannot resolve sk_value
    12.957: [warning] - QSslSocket: cannot resolve SSL_library_init
    12.957: [warning] - QSslSocket: cannot resolve SSL_load_error_strings
    12.957: [warning] - QSslSocket: cannot resolve SSL_get_ex_new_index
    12.957: [warning] - QSslSocket: cannot resolve SSLv3_client_method
    12.957: [warning] - QSslSocket: cannot resolve SSLv23_client_method
    12.957: [warning] - QSslSocket: cannot resolve SSLv3_server_method
    12.957: [warning] - QSslSocket: cannot resolve SSLv23_server_method
    12.957: [warning] - QSslSocket: cannot resolve X509_STORE_CTX_get_chain
    12.958: [warning] - QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
    12.958: [warning] - QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
    12.958: [warning] - QSslSocket: cannot resolve SSLeay
    12.958: [warning] - Incompatible version of OpenSSL
    23.097: [warning] - QSslSocket: cannot call unresolved function SSLv23_client_method
    23.097: [warning] - QSslSocket: cannot call unresolved function SSL_CTX_new
    23.097: [warning] - QSslSocket: cannot call unresolved function SSL_library_init
    23.097: [warning] - QSslSocket: cannot call unresolved function ERR_get_error
    23.098: [warning] - QSslSocket: cannot call unresolved function ERR_get_error
    23.098: [warning] - QSslSocket: cannot call unresolved function SSLv23_client_method
    23.098: [warning] - QSslSocket: cannot call unresolved function SSL_CTX_new
    23.098: [warning] - QSslSocket: cannot call unresolved function SSL_library_init
    23.099: [warning] - QSslSocket: cannot call unresolved function ERR_get_error
    23.099: [warning] - QSslSocket: cannot call unresolved function ERR_get_error
    28.522: [warning] - QSslSocket: cannot call unresolved function SSLv23_client_method
    28.523: [warning] - QSslSocket: cannot call unresolved function SSL_CTX_new
    28.523: [warning] - QSslSocket: cannot call unresolved function SSL_library_init
    28.523: [warning] - QSslSocket: cannot call unresolved function ERR_get_error
    28.523: [warning] - QSslSocket: cannot call unresolved function ERR_get_error

Parent is shutting down, bye...
user@host:~/Desktop$ 

```

**Comment by mujx** [comment] 2018-05-03 07:56
Duplicate of #156.

I will update the readme to make this more clear. There is small section at the moment https://github.com/mujx/nheko#linux

**Closed** 2018-05-03 09:40 UTC
