### ISSUE TITLE
FTBFS on Adelie/Alpine with gcc

### ISSUE THREAD

**Issue by Aerdan** [mujx/nheko#298] opened 2018-04-11 23:28 UTC
### System:

- Nheko commit/version: 0.3.0
- Installation method: Building from source
- Operating System: Adelie 1.0-alpha5/Alpine
- Qt version: 5.9
- C++ compiler: gcc 6.4
- Desktop Environment: 

### Actual behavior

Fails to build from source; log at https://dpaste.de/5ueL

### Expected behavior

Successfully builds and runs.

### Steps to reproduce

1. Install Adelie 1.0-alpha5 or Alpine 3.7 or edge
2. Install alpine-sdk (Alpine) or build-tools (Adelie). and Qt5 dev packages (use Alpine's package database to get package list for this)
3. Attempt to build nheko from source.

### Further notes

Codebase might be cleaner and more maintainable using a `std::pair<enum,basetype>` here.

**Comment by PureTryOut** [comment] 2018-04-12 06:46
This is a problem specific to GCC6, not so much to Alpine. Either use GCC7 or Clang to compile.

**Comment by mujx** [comment] 2018-04-12 07:47
That's indeed a problem with gcc but I haven't interpreted the error message yet (maybe there is fix on our side). The commit that introduced the problem is [this](https://github.com/mujx/nheko/commit/fef7cd5b8378a73de686688eb136faeb6246feb0) where I'm using `std::find_if` with a lambda predicate.

@Aerdan Using std::pair is indeed simpler but how would you enforce that only certain pairs are allowed?

**Comment by Aerdan** [comment] 2018-04-13 00:09
Talked with the fella who'd mentioned `std::pair<>` to me, and she explained the whole thing to me a bit more, and said she thinks the code would be more readable and maintainable with `dynamic_cast`. (I last touched C++ in 2003, for what it's worth...and it was a high school computer science course.)

**Comment by mujx** [comment] 2018-04-22 12:55
I've updated the readme with the supported compilers. Can we close this?

**Comment by PureTryOut** [comment] 2018-05-03 10:02
I'd say so. Distros wanting to package nheko just have to get a supported compiler, not much to do about it.

**Closed** 2018-05-03 10:04 UTC
